name: GSI-Workshop3

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    
env:
  ROM_URL: https://transfer.sh/1P9vYSD/Nusantara_v2.9-11-certus-17052021-OFFICIAL-1502.zip
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Dhaka

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
              
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/XenonTheInertG/XenonGSIs ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
          
       - name: Zip AB
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img

       - name: Upload AB 
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z
           name: GSI-Workshop-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}
           tag:  GSI-Workshop${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ github.run_number }}
           token: ${{ secrets.GHP }}

       - name: Upload A Only
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z
           name: GSI-Workshop-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}
           tag:  GSI-Workshop${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ github.run_number }}
           token: ${{ secrets.GHP }}
