me: GSI-Workshop2

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config2.env
      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.url }}" "URL config"
          required "${{ steps.config.outputs.rom_type }}" "ROM_TYPE config"
          required "${{ steps.config.outputs.zip_name }}" "ZIP_NAME config"
          required "${{ steps.config.outputs.mir }}" "MIR config"
        
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/XenonTheInertG/XenonGSIs ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh "${{ steps.config.outputs.url }}" "${{ steps.config.outputs.rom_type }}"
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/"${{ steps.config.outputs.zip_name }}"-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer "${{ steps.config.outputs.mir }}" ErfanGSIs/output/"${{ steps.config.outputs.zip_name }}"-GSI-Aonly.7z          
       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/"${{ steps.config.outputs.zip_name }}"-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer "${{ steps.config.outputs.mir }}" ErfanGSIs/output/"${{ steps.config.outputs.zip_name }}"-GSI-AB.7z      
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
