name: GSI-Workshop3

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config3.env
      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.url }}" "URL config"
          required "${{ steps.config.outputs.rom_type }}" "ROM_TYPE config"
          required "${{ steps.config.outputs.build_type }}" "BUILD_TYPE config"
          required "${{ steps.config.outputs.repack_name }}" "REPACK_NAME config"

      - name: Initialization environment
        run: |
            sudo -E apt-get -qq install git wget
       
      - name: Clone ErfanGSI Source Code
        run: git clone --recurse-submodules https://github.com/XenonTheInertG/XenonGSIs.git ErfanGSIs
       
      - name: Setting up ErfanGSI requirements with GSI Workshop setup script
        run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
              
      - name: Download Stock Rom & Generate GSI
        run: |
              sudo ./ErfanGSIs/url2GSI.sh "${{ steps.config.outputs.url }}" "${{ steps.config.outputs.rom_type }}" "${{ steps.config.outputs.build_type }}"
       
      - name: Zip GSI  
        run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/"${{ steps.config.outputs.repack_name }}"-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              zip -r ErfanGSIs/output/"${{ steps.config.outputs.repack_name }}"-GSI-AB.7z ErfanGSIs/output/*-AB-*.img               
              
      - name: Upload GSI to action-release.
        uses: softprops/action-gh-release@v1
        with:
           tag_name: test
           files: ${{ github.workspace }}/ErfanGSIs/build/*
